# Generated by Django 4.2.1 on 2023-07-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0006_rename_link_photo_news_photo_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='photo_link',
        ),
    ]
