# Generated by Django 4.2.1 on 2023-08-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0008_news_photo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo_link',
            field=models.URLField(default='https://htmlcolorcodes.com/assets/images/colors/light-gray-color-solid-background-1920x1080.png'),
        ),
    ]
