# Generated by Django 4.2.1 on 2023-07-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo_link', models.URLField(default='')),
                ('seller', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
